[package]
name = "chip8"
version = "1.0.0"
authors = ["Masato Bito <m@btmst.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "~0.4.11"
log4rs = "~0.13.0"
rand = "~0.7.3"
termion = "~1.5.5"
