[package]
name = "chip8"
version = "0.1.0"
authors = ["Masato Bito <m@btmst.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
log4rs = "*"
